<?xml version="1.0"?>
<?xacro?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="four_wheel_bot">

  <!-- Parameters -->
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="chassis_length" value="0.4"/>
  <xacro:property name="chassis_width" value="0.3"/>
  <xacro:property name="chassis_height" value="0.1"/>
  <xacro:property name="wheel_x_offset" value="${chassis_length / 2 - wheel_radius}"/>
  <xacro:property name="wheel_y_offset" value="${chassis_width / 2 - wheel_radius}"/>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <origin xyz="0 0 ${chassis_height / 2}" rpy="0 0 0"/>
      <material name="gray"><color rgba="0.5 0.5 0.5 1"/></material>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <origin xyz="0 0 ${chassis_height / 2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="20"/>
      <origin xyz="0 0 0.02" rpy="0 0 0"/>
      <inertia ixx="0.3" ixy="0" ixz="0" iyy="0.3" iyz="0" izz="0.3"/>
    </inertial>
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <!-- Wheel Macro -->
  <xacro:macro name="wheel" params="name x y">
    <link name="${name}_link">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <material name="black"><color rgba="0 0 0 1"/></material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      </collision>
      <inertial>
        <mass value="1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
      </inertial>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <origin xyz="${x} ${y} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Wheels -->
  <xacro:wheel name="front_left_wheel" x="${wheel_x_offset}" y="${wheel_y_offset}"/>
  <xacro:wheel name="front_right_wheel" x="${wheel_x_offset}" y="${-wheel_y_offset}"/>
  <xacro:wheel name="rear_left_wheel" x="${-wheel_x_offset}" y="${wheel_y_offset}"/>
  <xacro:wheel name="rear_right_wheel" x="${-wheel_x_offset}" y="${-wheel_y_offset}"/>

  <!-- Gazebo materials for wheels -->
  <gazebo reference="front_left_wheel_link">
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="front_right_wheel_link">
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="rear_left_wheel_link">
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="rear_right_wheel_link">
    <material>Gazebo/Black</material>
  </gazebo>

  <!-- LIDAR -->
  <link name="lidar_link">
    <visual>
      <geometry><cylinder radius="0.03" length="0.02"/></geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="green"><color rgba="0 1 0 1"/></material>
    </visual>
    <collision>
      <geometry><cylinder radius="0.03" length="0.02"/></geometry>
      <origin xyz="0 0 0.12" rpy="0 0 0"/>
    </collision>
  </link>
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 0.12" rpy="0 0 0"/>
  </joint>

  <gazebo reference="lidar_link">
    <material>Gazebo/Green</material>
    <sensor type="ray" name="lidar_sensor">
      <update_rate>30</update_rate>
      <visualize>true</visualize>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.5708</min_angle>
            <max_angle>1.5708</max_angle>
          </horizontal>
        </scan>
        <range><min>0.12</min><max>3.5</max></range>
      </ray>
      <plugin name="gazebo_ros_laser" filename="libgazebo_ros_ray_sensor.so">
        <ros><namespace>/four_wheel_bot</namespace></ros>
        <topicName>scan</topicName>
        <frameName>lidar_link</frameName>
        <output_type>sensor_msgs/LaserScan</output_type>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Camera -->
  <link name="camera_link">
    <visual>
      <geometry><box size="0.04 0.04 0.04"/></geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="blue"><color rgba="0 0 1 1"/></material>
    </visual>
    <collision>
      <geometry><box size="0.04 0.04 0.04"/></geometry>
      <origin xyz="0 0 0.2" rpy="0 0 0"/>
    </collision>
  </link>
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${chassis_length / 2 - 0.02} 0 ${chassis_height + 0.03}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="camera_link">
    <material>Gazebo/Blue</material>
    <sensor type="camera" name="camera_sensor">
      <update_rate>30</update_rate>
      <visualize>true</visualize>
      <camera>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip><near>0.1</near><far>100</far></clip>
      </camera>
      <plugin name="gazebo_ros_camera_controller" filename="libgazebo_ros_camera.so">
        <ros><namespace>/four_wheel_bot</namespace></ros>
        <cameraName>camera</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Differential Drive Plugin with speed limit -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <ros><namespace>/four_wheel_bot</namespace></ros>
      <left_joint>rear_left_wheel_joint</left_joint>
      <right_joint>rear_right_wheel_joint</right_joint>
      <wheel_separation>${2 * wheel_y_offset}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <wheel_diameter>${2 * wheel_radius}</wheel_diameter>
      <cmd_vel_topic>cmd_vel</cmd_vel_topic>
      <odometry_topic>odom</odometry_topic>
      <publish_odom>true</publish_odom>
      <max_velocity>0.5</max_velocity>
      <max_acceleration>1.0</max_acceleration>
    </plugin>
  </gazebo>

</robot>

